### ISSUE TITLE
Bug: error: [dial tcp4 192.168.x.x:57xxx: connectex: No connection could be made because the target machine actively refused

### ISSUE THREAD

**Issue by nakhla** [quackduck/uniclip#11]
I have just came across this tool and i think it will be awesome as it should work in  windows, linux, android, and termux
unfortunately, i t doesn't work in my windows machine, and i got this error
error: [dial tcp4 192.168.1.30:57067: connectex: No connection could be made because the target machine actively refused it.]
Could not connect to 192.168.1.30:57067

**Comment by quackduck** [comment]
Are both machines on the same LAN?

**Comment by nakhla** [comment]
oh, that is my fault, will try again and update you again in 2 minutes

**Comment by quackduck** [comment]
okay so the way uniclip works is you first run `uniclip` on one machine (keep that command running) and then run the command it tells you to run (`uniclip <ip>:<port>`)

**Comment by quackduck** [comment]
The machine you start from (the one running only `uniclip`) is like the "server" and is the "clipboard host", and the command it tells you to run is what a "client" can use to connect to the server.

**Comment by quackduck** [comment]
I'm glad it works! There is no APK I've made, it's available as an executable that you can run using termux

**Comment by nakhla** [comment]
tried using termux, after installed the termux-api but with no luck, i used "ClipSync" but i liked yours because it is available under Linux, just an APK will be great,

**Comment by quackduck** [comment]
Did uniclip not work with termux?

**Comment by nakhla** [comment]
i downloaded it and insure it has chmod +x, and it running but it is not function

**Comment by nakhla** [comment]
ok i will, also FYI, i am using a bit old termux 0.83, for android 6 marshmallow
