### ISSUE TITLE
Recognized as a virus by ESET

### ISSUE THREAD

**Issue by nakhla** [quackduck/uniclip#12]
A suspicious object is an object (file) which has been blacklisted in cloud.
unclip file is deleted

**Comment by quackduck** [comment]
This is not a bug here, but in fact in whatever antivirus software detected this as a virus

**Comment by quackduck** [comment]
Windows thinks all Go binaries are malware, 😆 
I'm guessing ESET does something similar

**Comment by quackduck** [comment]
Closing this
