### ISSUE TITLE
Bug: Contents sent but not received

### ISSUE THREAD

**Issue by dasistkeintest** [quackduck/uniclip#15]
I am trying to connect my laptop (Windows 11) and my phone (Android 12) using version 2.3.5.
The initial connection works as expected, but the clipboard isn't synchronized.
In debug mode both instances report sending the clipboard contents, but apparently they don't receive anything.

**Comment by KlugFR** [comment]
Same issue with 2.35 (using the release binary) between a Windows 10 laptop and a MacBook Air M1 running Ventura 13.1.
Initiation works (the two "sees" each other).
Debug shows the clipboard contents are sent (both ways) but not received

**Comment by quackduck** [comment]
That's very strange, I will try to reproduce it.

**Comment by KlugFR** [comment]
I'll try to do some additional testing with another laptop running Win7.

**Comment by Tortue95** [comment]
The problem is coming from the `setLocalClip()` function on Windows. 

The variable "s" is no longer being set, which is causing an empty string to be forced into the clipboard. 
there is no `-Value` in the powershell command and no pipe executed for windows.

I have gone back to the previous code:
`copyCmd = exec.Command("powershell.exe", "-command", "Set-Clipboard -Value "+"\""+s+"\"")`

**Comment by Tortue95** [comment]
To make it work without the `--secure` flag, the `clipboardBytes` variable in the `sendClipboard()` function must be filled with the data that we want to send. However, this is not the case.

I have therefore corrected the code by:
```
	if secure {
		...
	} else {
		clipboardBytes = []byte(clipboard)
	}
```

**Comment by Tortue95** [comment]
for Windows To avoid issues with escaping in the `setLocalClip()` function, I use the `clip` command instead and enable the "pipe".
like this:

```
func setLocalClip(s string) {
	var copyCmd *exec.Cmd
	switch runtime.GOOS {
	case "windows":
		copyCmd = exec.Command("clip")
	default:
		...
	}
	in, err := copyCmd.StdinPipe()
	if err != nil {
		handleError(err)
		return
	}
	if err = copyCmd.Start(); err != nil {
		handleError(err)
		return
	}
	if _, err = in.Write([]byte(s)); err != nil {
		handleError(err)
		return
	}
	if err = in.Close(); err != nil {
		handleError(err)
		return
	}
	if err = copyCmd.Wait(); err != nil {
		handleError(err)
		return
	}
}
```

**Comment by KlugFR** [comment]
Wow, nice work!

**Comment by KlugFR** [comment]
@quackduck, sorry to ask this way but could you please integrate the suggested patch and provide new binaries?

**Comment by meliksah** [comment]
I did required changes here: https://github.com/meliksah/uniclip/releases/tag/v2.3.6

**Comment by quackduck** [comment]
Should work now!!!!

**Comment by meliksah** [comment]
it is working for me in secure mode

**Comment by quackduck** [comment]
Does it not work in the regular mode?

**Comment by quackduck** [comment]
I forgot to release lol. Try the latest commit.

**Comment by quackduck** [comment]
Yes that’s what I meanOn Mar 21, 2023, at 10:44 AM, SalmonSays ***@***.***> wrote:﻿
Perhaps I'm being obtuse, but how do I go about doing that? The latest release appears to still be from April. Do you mean compiling it from source?

**Comment by quackduck** [comment]
@SalmonSays I finally got around to releasing the fix. v2.3.6 has it. LMK if it works

**Comment by clst** [comment]
Does not seem to work for me. I can send from Linux to Windows but Windows only prints:

```
error: [exit status 1]
```
in a loop.

What powershell do you need?

```
powershell.exe -command Get-Clipboard
The term 'Get-Clipboard' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name,
or if a path was included, verify that the path is correct and try again.
At line:1 char:14
+ Get-Clipboard <<<<
    + CategoryInfo          : ObjectNotFound: (Get-Clipboard:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Is there an alternative to powershell? Seems pretty wasteful. Go cannot access the clipboard or Win32 API directly?

Sorry for the dumb question I never did a project in Go (yet).
