### ISSUE TITLE
Bug: EOF error on windows

### ISSUE THREAD

**Issue by Geczy** [quackduck/uniclip#17]
on my windows:

```bash
~/desktop
$ ./uniclip.exe
Starting a new clipboard
Run `uniclip 192.168.0.178:53533` to join this clipboard

Connected to device at 192.168.0.229:62305
error: [gob: duplicate type received]
error: [gob: duplicate type received]
error: [gob: decoding into local type *[]uint8, received remote type unknown type]
error: [gob: duplicate type received]
error: [gob: duplicate type received]
error: [unexpected EOF]
```

in safari on my iphone: "cancelled load from .... beacuse it is using http/0.9"

**Comment by quackduck** [comment]
Did you try to visit `192.168.0.178:53533` in a web browser on your iPhone?

**Comment by Geczy** [comment]
yes how do i use this on my iphone ?

**Comment by quackduck** [comment]
Unfortunately uniclip does not work on iPhones because Apple does not allow running executables directly

**Comment by quackduck** [comment]
If you have a Mac tho you can use Apple's own clipboard syncing

**Comment by Geczy** [comment]
i know, but i need clipboard syncing on windows lol

**Comment by quackduck** [comment]
yeahhhh... unfortunately apple makes running stuff on iphone pretty annoying

**Comment by alx-xlx** [comment]
Why not create a webserver or websocket of some sort and then make it accessible using URL. If someone doesn't have a macOS they can use siri to run the shortcut that will have automation to grab the copied texts from the local webserver or websocket.

And vice versa. Where the iOS device will POST the clipboard to the local server and so on.

**Comment by quackduck** [comment]
uniclip works fine on macOS.

about iOS, I'm not sure whether sites on iOS can fetch clipboard data in the background. Do you know?

**Comment by alx-xlx** [comment]
With Apple Shortcuts clipboard can be set and read from web requests. But triggerring them will have to be manual. However, with the help of siri you can execute the shortcut using voice command when ever something is copied.

https://github.com/changkun/midgard/blob/main/docs/usage.md
This is the tool that does the similar thing

Yes, uniclip works perfectly fine with macOS + iOS, using Handoff feature enabled. However if someone don't have a macOS or if the device if turned oFF then it would be an issue for them to use this tool
