### ISSUE TITLE
it is wonderful! but how it can support Chinese?

### ISSUE THREAD

**Issue by jerryzhai26** [quackduck/uniclip#2]
how it can support Chinese?

**Comment by quackduck** [comment]
Hello! I do not currently have support for Chinese. I could add support by using an online translate service. I am not sure how Uniclip would detect the language settings.

**Comment by quackduck** [comment]
Of course, if you would like to help translate it to Chinese, you may open a pull request :)

**Comment by quackduck** [comment]
The interface is quite minimal: when the executable is run, a command enclosed in back-ticks (`) appears. Running this command on the other device will connect the two.

**Comment by veryniceperson** [comment]
cool

**Comment by veryniceperson** [comment]
DOES IT SUPPORT RUSSIAN

**Comment by quackduck** [comment]
> Hello! I do not currently have support for Chinese. I could add support by using an online translate service. I am not sure how Uniclip would detect the language settings.

> Of course, if you would like to help translate it to Chinese, you can open a pull request! :)

> The interface is quite minimal: when the executable is run, a command enclosed in backticks (`) appears. Running this command on the other device will connect the two.

@veryniceperson Sorry, I don't have support for any languages other than English right now

**Comment by quackduck** [comment]
Let me know what I should do @jerryzhai26.

**Comment by quackduck** [comment]
Is your fork related to this issue, @jerryzhai26?

**Comment by jerryzhai26** [comment]
> Is your fork related to this issue, @jerryzhai26?
really sorry, i did't notice your message because i rarely click the notifications. actually ,it is the first time i report the issues.
Thank you for your enthusiasm. but my fork is not related to this issue.
and i don think i  have the ability to add the language interface.
sincerely sorry

**Comment by quackduck** [comment]
That's completely alright! What is your fork for then, @jerryzhai26?

(I made an edit for removing the non-quote part from the quote part)

**Comment by quackduck** [comment]
@jerryzhai26 let me know of any updates on this.
