### ISSUE TITLE
Does not work on Big Sur

### ISSUE THREAD

**Issue by tyler-morales** [quackduck/uniclip#3]

**Comment by quackduck** [comment]
Please provide more details.
What exactly is the behavior observed?
What output do you see when using the verbose `-v` option?

Thanks for your interest! :)
(I currently am on Big Sur and it does work for me)

**Comment by tyler-morales** [comment]
It was an issue with my CLT. Once I updated it, the issue was resolved.

**Comment by quackduck** [comment]
Out of curiosity, what exactly was the issue? I don't see how command line tools are related to uniclip. I don't think pbcopy or pbpaste are part of those.
