### ISSUE TITLE
Bug: `-p` command line option seems to be ignored

### ISSUE THREAD

**Issue by belowm** [quackduck/uniclip#30]
**Description of the bug**
If I understand correctly, `-p` should start uniport listening on the specified port. However, it still chooses a random port (v.2.3.6). The given port is definitely not bound by another processes.

I've noticed that `-p` is not mentioned in `--help`. However, it is given as an example in [README.md](https://github.com/quackduck/uniclip/blob/master/README.md):
```
uniclip -p 53701                          # start a new clipboard on the provided port
```

**Verbose output (Use the `--debug` option)**
```bash
$ uniclip --version
v2.3.6

$ uniclip --debug -p 6666
Starting a new clipboard
Run `uniclip 192.168.178.112:46515` to join this clipboard
```

**OS and Uniclip version**
v2.3.6

**Comment by belowm** [comment]
By looking into the source file for v2.3.6 tag, I realized that this options is not part of v.2.3.6.

**Comment by robertpro** [comment]
@belowm so what did you do? used a differente version ?

**Comment by aldoanizio** [comment]
> [@belowm](https://github.com/belowm) so what did you do? used a differente version ?

I've solved it compiling it from master branch.

If you have docker installed clone the repository and execute it:

docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app golang:latest go build -o uniclip uniclip.go

This will create a "uniclip" binary file.

So after this you move "uniclip" file to /usr/bin/uniclip and give execution permission:

sudo chmod +x /usr/bin/uniclip


I'm running the compiled version from master branch so far and no problems untill now.
