### ISSUE TITLE
Uniclip not sending clipboard when Termux loses focus

### ISSUE THREAD

**Issue by muralikodali** [quackduck/uniclip#6]
uniclip without sudo failing to start with following error :  

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4fce97]

goroutine 1 [running]:
main.connectToServer(0x7ffcab4ca8ab, 0x11)
	/Users/ishan/Desktop/GitHub/Go/uniclip/uniclip.go:97 +0x77
main.main()
	/Users/ishan/Desktop/GitHub/Go/uniclip/uniclip.go:59 +0x269
main.main()
	/Users/ishan/Desktop/GitHub/Go/uniclip/uniclip.go:51 +0x193
```

**Comment by quackduck** [comment]
Looking into this issue. Please include output with the `--debug` option.

**Comment by quackduck** [comment]
Exactly what was the command you ran?

**Comment by quackduck** [comment]
@muralikodali try updating to v2.0.3 (https://github.com/quackduck/uniclip/releases/v2.0.3) or use `brew upgrade uniclip` if you're on macOS.

**Comment by quackduck** [comment]
The error could happen if you were attempting to connect to a nonexistent address. First you need to start a clipboard with `uniclip` and then connect to the address it prints out:
```
ishan@mac [~] |>  uniclip
Starting a new clipboard
Run `uniclip 192.168.86.24:50739` to join this clipboard
```

**Comment by muralikodali** [comment]
After running 3-4 times, it's not failing now. I am not able to find out the reason.

in my setup, i have connected linux system (Arch Linux) with Android 10 .

when termux window is losing focus on Android , it not transferring copied text to my linux system and transferring text only after termux window getting focus, while text copied on linux system is immediately transferred to Android clipboard.

**Comment by quackduck** [comment]
Try letting Termux run in the background: https://support.hydrawise.com/hc/en-us/articles/360022280353-Android-App-Run-in-Background-Option-

**Comment by quackduck** [comment]
Let me know if anything comes up.

**Comment by muralikodali** [comment]
working as intended
problem with termux is android related

**Comment by quackduck** [comment]
👍
